swagger: "2.0"
info:
  description: "This is a sample reactive server that use Redis PubSub system in order to update a reactive endpoint."
  version: "1.0.0"
  title: "Reactive Redis"
  termsOfService: "https://github.com/jesty"
  contact:
    email: "davidecerbo@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/api"
schemes:
- "https"
- "http"
paths:
  /ticker:
    get:
      description: "Tick every second"
      operationId: "tick"
      consumes:
      - "application/json"
      produces:
      - "text/event-stream"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              type: number

  /items:
    get:
      description: "Live items list"
      parameters:
      - name: "filter"
        in: "query"
        description: "Value that must be in name string"
        type: string
      operationId: "listItems"
      consumes:
      - "application/json"
      produces:
      - "text/event-stream"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Item"

definitions:
  Item:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: "1"
      name:
        type: string
        example: "Item One"